### ISSUE TITLE
New technology: compressing

### ISSUE THREAD

**Issue by jetschni** [jetschni/test-repository#19]
# Submission
Submitted at 2021-12-09T20:25:27.593Z via tally.so form
### Submitter
**Name:** cross-platform
### Submission
**Technology name:** compressing
**Description:** withdrawal
**Website:** http://tamia.org
**Twitter:** back-end
**GitHub:** Investor
**Token:** bus
**Logo:** http://skyla.net/images/bus.png
**Layer:** Experience
**Categories:** Reactive
**Does the technology focuses primarily on the metaverse?** Yes

# Add submission to the landscape
For more details how to contribute see [here](https://github.com/mscape/mscape#contribute)
### 1) Add logo
Add the logo in the respective logo folder `logos/technology`/. Filename becompressing.svg`. SVG images with transparent background are preferred.

### 2) Create new file
Create following file in `projects`

`compressing.yml`:
```yaml
name: compressing
description: withdrawal
website: http://tamia.org
twitterHandle: back-end
logo: logos/technologies/compressing.svg
layer: Experience
categories:Reactive
metaverseNative: Yes
token: bus
publish: 1
```

### 3) Create a new Pull Request 
Create a Pull Request with your commited changes. Your pull request message should start with `Contribution: {NAMES}` - NAMES can be a list of names. If you have multiple contributions, you can add them all in one pull request. We will review it and publish it as soon as possible.
