### ISSUE TITLE
New technology: array

### ISSUE THREAD

**Issue by jetschni** [jetschni/test-repository#22]
# Submission
Submitted at 2021-04-03T21:52:21.492Z via tally.so form
### Submitter
**Name:** Concrete
### Submission
**Technology name:** array
**Description:** Personal Loan Account
**Website:** https://lorenzo.net
**Twitter:** Tasty Granite Car
**GitHub:** Electronics
**Token:** Sleek Granite Fish
**Logo:** https://dave.biz/images/Fantastic.png
**Layer:** Experience
**Categories:** web-readiness
**Does the technology focuses primarily on the metaverse?** Yes

# Add submission to the landscape
For more details how to contribute see [here](https://github.com/mscape/mscape#contribute)
### 1) Add logo
Add the logo in the respective logo folder `logos/technology`/. Filename be array.svg. SVG images with transparent background are preferred.

### 2) Create new file
Create following file in `projects`

`array.yml`:
```yaml
name: array
description: Personal Loan Account
website: https://lorenzo.net
twitterHandle: Tasty Granite Car
logo: logos/technologies/array.svg
layer: Experience
categories:web-readiness
metaverseNative: Yes
token: Sleek Granite Fish
publish: 1
```

### 3) Create a new Pull Request 
Create a Pull Request with your commited changes. Your pull request message should start with `Contribution: {NAMES}` - NAMES can be a list of names. If you have multiple contributions, you can add them all in one pull request. We will review it and publish it as soon as possible.
