### ISSUE TITLE
New project: Home Loan Account

### ISSUE THREAD

**Issue by jetschni** [jetschni/test-repository#23]
# Submission
Submitted at 2021-03-08T05:10:32.193Z via tally.so form
### Submitter
**Name:**  infrastructure
### Submission
**Project name:** Home Loan Account
**Description:** Operations
**Twitter:** invoice
**GitHub:** synergistic
**Logo:** https://reuben.org/images/methodical.png
**What is the status of the project?** Announced
**Is the project focused and branded as metaverse?** Yes
**Does the project is a 3D world?** Yes
**Does the project offer a open world to its users?** Yes
**Can user create their own content?** Yes
**How can user access the project?** VR

# Add submission to the landscape
For more details how to contribute see [here](https://github.com/mscape/mscape#contribute)
### 1) Add logo
Add the logo in the respective logo folder `logos/projects`/. Filename be Home Loan Account.svg`. SVG images with transparent background are preferred.

### 2) Create new file
Create following file in `projects`

`Home Loan Account.svg`:
```yaml
name: Home Loan Account
description: Operations
website: 
twitterHandle: invoice
logo: https://reuben.org/images/methodical.png
status: Announced
category: Virtual world
metaverseNative: Yes
threeD: Yes
openWorld: Yes
userContent: Yes
access: VR
token: Metal
publish: 1
```

### 3) Create a new Pull Request 
Create a Pull Request with your commited changes. Your pull request message should start with `Contribution: {NAMES}` - NAMES can be a list of names. If you have multiple contributions, you can add them all in one pull request. We will review it and publish it as soon as possible.
