### ISSUE TITLE
New project submission: Mobility

### ISSUE THREAD

**Issue by jetschni** [jetschni/test-repository#9]
# Submission
Submitted at 2021-03-17T02:17:49.089Z via tally.so form

### Submitter
**Name:**  distributed
### Submission
**Project name:** Mobility
**Description:** engineer
**Twitter:** Operations
**GitHub:** system
**Logo:** http://amely.biz/images/National.png
**What is the status of the project?** Announced
**Is the project focused and branded as metaverse?** Yes
**Does the project is a 3D world?** Yes
**Does the project offer a open world to its users?** Yes
**Can user create their own content?** Yes
**How can user access the project?** VR

# Add submission to the landscape
For more details how to contribute see [here](https://github.com/mscape/mscape#contribute)
### Add logo
Add the logo in the respective logo folder `logos/projects`/. Filename be Mobility.yml`. SVG images with transparent background are preferred.
### Create new file
Create following file in `projects`
`Mobility.yml`:
```yaml
name: Mobility
description: engineer
website: https://decentraland.org
twitterHandle: Operations
logo: logos/projects/Mobility.svg
status: Announced
category: Open virtual world
metaverseNative: Yes
threeD: Yes
openWorld: Yes
userContent: Yes
access: VR
token: N/A
publish: 1
```

### Create a new Pull Request 

Create a Pull Request with your commited changes. Your pull request message should start with `Contribution: {NAMES}` - NAMES can be a list of names. If you have multiple contributions, you can add them all in one pull request. We will review it and publish it as soon as possible.

### Conventions

Please follow the following conventions:
- Data sets must always be lowercase without any special characters or spaces with file suffix `.yml`
- Logos must be placed in logos/{project/technologies} directory
- Logo filenames must always be lowercase without any special characters or spaces and should be added to respective YAML file as a URL
- Logos should always be SVG images if available, otherwise use PNG with transparent background
- Twitter handles must not contain a #
- GitHub links must follow the structure `{ORGANIZATION}/{REPOSITORY}`
